version: '{build}'
max_jobs: 1
image: WMF 5
clone_depth: 5
branches:
  only:
    - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch
  # name to use development version from Github
  au_version:
  au_push: true

  # Github token to commit pushed packages to repository
  github_user_repo: nverno/chocolatey-packages
  github_api_key:
    # https://ci.appveyor.com/tools/encrypt
    secure: VKZpa7UyxudWUNVNiUXwgRnd+Cjux1GPsGUL79OUkVM1qKh//0kXbJH1bG2r0zZf

  # Mail credentials - for error notifications
  mail_user:
    secure: twFoJrwqyN3UM/pGtuGz++cV8dbbeWQi+lAHzxN1Ifk=
  mail_pass:
    secure: FWsn4jLjVHGqbH25CrHN/A==
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the
  # github_user (secret or not) and grab the id - https://gist.github.com/name/id
  # Optional, leave empty to create anonymous gist
  gist_id: 97a0f42da54bac1667a071e36faf3fe8

  # Chocolatey API key - to push updated packages
  api_key:
    secure: AgufNGyvomVqgmRIHviTqRaYoYlVsgNsN23+OoLKQMygySl24xg1439cRqpnL4N6

init:
  - git config --global user.email "chocolatey@realdimensions.net"
  - git config --global user.name  "Chocolatey"
  - git config --global core.safecrlf false

install:
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - ps: |
    $x=$null; $is_branch = ($Env:au_version -ne $null) -and ([version]::TryParse($Env:au_version, [ref]$x) -eq $false)
    if ($is_branch) {
        pushd ..
            git clone -q https://github.com/majkinetor/au.git
            cd au
            git fetch
            git checkout -q $Env:au_version
            ./build.ps1 -Install -NoChocoPackage
        popd
    } else {
        Install-PackageProvider -Name NuGet -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

        $params = @{ Name = 'au' }
        if ( $Env:au_version -ne $null ) { $params.MinimumVersion = $Env:au_version }
        Install-Module @params

        Get-Module au -ListAvailable | select Name, Version
    }

build_script:
  - ps: |
    ./au/update_all.ps1

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: au/update_info.xml
  - path: au/Update-AUPackages.md

notifications:
  - provider: Email
    to: $(mail_user)
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

